### PR TITLE
Added zips for react-json-tree

### PR DESCRIPTION
**Pull request by jakubkarabula**

### CODE REVIEW

**Comment by borys-cl** [comment]
I checked out to your PR that is dependent on this one, changed the location of the packages to point to the files in this PR. I ran `npm i` to install it, everything went fine. Now when I try to `npm run start` it claims that `react-json-tree` can't be resoved. I believe something is wrong with the package itself. @skizhak ?

**Comment by borys-cl** [comment]
With these files the build fails with a red wall of errors about packages resolution... @skizhak can you help Jakub?

**Comment by borys-cl** [comment]
P.S. the md5 checksums does not match in dependent PR so you need to update them after you changed the files.

**Comment by skizhak** [comment]
@biswajit-mandal can you pls take a look. thanks

**Comment by borys-cl** [comment]
@biswajit-mandal this is a PR that requires this package: https://github.com/Juniper/jws/pull/511

**Comment by biswajit-mandal** [comment]
1. Looks like the packages added are not made using "--global-style", please run the below two commands to get the packages:
npm install --global-style react-json-tree@0.11.0
npm install --global-style @types/react-json-tree@0.6.6
Then make tar package and upload once again.

2. To pass the test cases as in https://github.com/Juniper/jws/pull/511, please get this pull request (https://github.com/Juniper/contrail-ui-third-party-cache/pull/6) merged and then start jws/511 pull request, it should pass. Currently in 511, make deps fails, as it tries to download the packages react-json-tree, which is not available yet.

**Pull request merged**
